---
- name: create files
  hosts: localhost
  tasks: 
    - name: create files on localhost
      files:
        name: repo.json
        state: touch
    - name: enter some content in json file
      copy:
        content: "remote_url": "https://github.com/surendra2309/ansible-project-1.git"
        dest: repo.json 